### PR TITLE
Making library AOT compatible

### PR DESCRIPTION
**Pull request by kshkrao3**
Below zip file contains aot related settings for the library

[aot-compat.zip](https://github.com/matheushf/ng2-date-countdown/files/1696338/aot-compat.zip)

### CODE REVIEW

**Comment by matheushf** [comment]
Thanks!

I'm quite busy now, but soon I'll review this PR

**Comment by kshkrao3** [comment]
@matheushf Sure, please. I will be waiting,

**Comment by matheushf** [comment]
Actually it wasn't enough, I'm changing the lib and the way I'm building it, but still not luck with AOT.
I'm waiting for some answers in some issues now to get back to it.

**Comment by kshkrao3** [comment]
@matheushf May I know what's the issue you are facing? I've been through a lot before getting this to work and I'll try to help.

**Comment by matheushf** [comment]
#6

**Comment by timelf123** [comment]
@kshkrao3 check out #6

**Comment by kshkrao3** [comment]
Is this fixed? Sorry for the delay. I was quite busy with other projects.. :(

**Comment by kshkrao3** [comment]
@matheushf Anything useful on this thread?
https://github.com/angular/angular/issues/10789

**Comment by kshkrao3** [comment]
@matheushf  I feel that the package should not be including `node_modules` after its is built. All the necessary packages should be in root `node_modules`  specifically dependencies for `angular` related libraries.

**Pull request closed without merging**
